# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/lenovo/source/AP_1/AP_Task2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/lenovo/source/AP_1/AP_Task2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lenovo/source/AP_1/AP_Task2/CMakeFiles /mnt/c/Users/lenovo/source/AP_1/AP_Task2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lenovo/source/AP_1/AP_Task2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AP_Task2

# Build rule for target.
AP_Task2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AP_Task2
.PHONY : AP_Task2

# fast build rule for target.
AP_Task2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/build
.PHONY : AP_Task2/fast

CalcDist.o: CalcDist.cpp.o
.PHONY : CalcDist.o

# target to build an object file
CalcDist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/CalcDist.cpp.o
.PHONY : CalcDist.cpp.o

CalcDist.i: CalcDist.cpp.i
.PHONY : CalcDist.i

# target to preprocess a source file
CalcDist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/CalcDist.cpp.i
.PHONY : CalcDist.cpp.i

CalcDist.s: CalcDist.cpp.s
.PHONY : CalcDist.s

# target to generate assembly for a file
CalcDist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/CalcDist.cpp.s
.PHONY : CalcDist.cpp.s

KNN.o: KNN.cpp.o
.PHONY : KNN.o

# target to build an object file
KNN.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/KNN.cpp.o
.PHONY : KNN.cpp.o

KNN.i: KNN.cpp.i
.PHONY : KNN.i

# target to preprocess a source file
KNN.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/KNN.cpp.i
.PHONY : KNN.cpp.i

KNN.s: KNN.cpp.s
.PHONY : KNN.s

# target to generate assembly for a file
KNN.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/KNN.cpp.s
.PHONY : KNN.cpp.s

Point.o: Point.cpp.o
.PHONY : Point.o

# target to build an object file
Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/Point.cpp.o
.PHONY : Point.cpp.o

Point.i: Point.cpp.i
.PHONY : Point.i

# target to preprocess a source file
Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/Point.cpp.i
.PHONY : Point.cpp.i

Point.s: Point.cpp.s
.PHONY : Point.s

# target to generate assembly for a file
Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/Point.cpp.s
.PHONY : Point.cpp.s

PointReader.o: PointReader.cpp.o
.PHONY : PointReader.o

# target to build an object file
PointReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/PointReader.cpp.o
.PHONY : PointReader.cpp.o

PointReader.i: PointReader.cpp.i
.PHONY : PointReader.i

# target to preprocess a source file
PointReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/PointReader.cpp.i
.PHONY : PointReader.cpp.i

PointReader.s: PointReader.cpp.s
.PHONY : PointReader.s

# target to generate assembly for a file
PointReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/PointReader.cpp.s
.PHONY : PointReader.cpp.s

SafetyChecks.o: SafetyChecks.cpp.o
.PHONY : SafetyChecks.o

# target to build an object file
SafetyChecks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/SafetyChecks.cpp.o
.PHONY : SafetyChecks.cpp.o

SafetyChecks.i: SafetyChecks.cpp.i
.PHONY : SafetyChecks.i

# target to preprocess a source file
SafetyChecks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/SafetyChecks.cpp.i
.PHONY : SafetyChecks.cpp.i

SafetyChecks.s: SafetyChecks.cpp.s
.PHONY : SafetyChecks.s

# target to generate assembly for a file
SafetyChecks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/SafetyChecks.cpp.s
.PHONY : SafetyChecks.cpp.s

ex2.o: ex2.cpp.o
.PHONY : ex2.o

# target to build an object file
ex2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/ex2.cpp.o
.PHONY : ex2.cpp.o

ex2.i: ex2.cpp.i
.PHONY : ex2.i

# target to preprocess a source file
ex2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/ex2.cpp.i
.PHONY : ex2.cpp.i

ex2.s: ex2.cpp.s
.PHONY : ex2.s

# target to generate assembly for a file
ex2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AP_Task2.dir/build.make CMakeFiles/AP_Task2.dir/ex2.cpp.s
.PHONY : ex2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AP_Task2"
	@echo "... CalcDist.o"
	@echo "... CalcDist.i"
	@echo "... CalcDist.s"
	@echo "... KNN.o"
	@echo "... KNN.i"
	@echo "... KNN.s"
	@echo "... Point.o"
	@echo "... Point.i"
	@echo "... Point.s"
	@echo "... PointReader.o"
	@echo "... PointReader.i"
	@echo "... PointReader.s"
	@echo "... SafetyChecks.o"
	@echo "... SafetyChecks.i"
	@echo "... SafetyChecks.s"
	@echo "... ex2.o"
	@echo "... ex2.i"
	@echo "... ex2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

